<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HL6T2B3" failures="1" tests="3" name="JavaMavenTestNG.JavaMavenTestNG.NewTest" time="73.863" errors="0" timestamp="2024-12-13T22:44:55 CST" skipped="0">
  <testcase classname="JavaMavenTestNG.JavaMavenTestNG.NewTest" name="test1" time="73.860">
    <failure message="assert - ASSERT TRUE CHECKfalse expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: assert - ASSERT TRUE CHECKfalse expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at JavaMavenTestNG.JavaMavenTestNG.Test1.verifyTextPresent(Test1.java:2402)
at JavaMavenTestNG.JavaMavenTestNG.NewTest.test1(NewTest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <system-out>
    <![CDATA[<a href='C:\Users\pvenkatarajan\GIT2\PVautomation02\JavaMavenTestNG/screenshots/test1.png' target='_blank'>Screenshot</a>

REPORTER for fail in listner1
]]>
  </system-out>
  <testcase classname="JavaMavenTestNG.JavaMavenTestNG.NewTest" name="test2" time="0.002"/>
  <system-out>
    <![CDATA[

<a href='C:\Users\pvenkatarajan\GIT2\PVautomation02\JavaMavenTestNG/screenshots/test2.png' target='_blank'>Screenshot</a>



REPORTER for pass in listner1
]]>
  </system-out>
  <testcase classname="JavaMavenTestNG.JavaMavenTestNG.NewTest" name="test3" time="0.001"/>
  <system-out>
    <![CDATA[

<a href='C:\Users\pvenkatarajan\GIT2\PVautomation02\JavaMavenTestNG/screenshots/test3.png' target='_blank'>Screenshot</a>



REPORTER for pass in listner1
]]>
  </system-out>
</testsuite> <!-- JavaMavenTestNG.JavaMavenTestNG.NewTest -->
